CFLAGS = -ansi -g -Wall -O3

all: ex101.o \
	ex102.o \
	ex103.o \
	ex104.o \
	ex105.o \
	ex106.o \
	ex107.o \
	ex108.o \
	ex109.o \
	ex110.o \
	ex112.o \
	ex113.o \
	ex114.o \
	ex115.o \
	ex116.o \
	ex117.o

ex101.o: ex101.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex102.o: ex102.c
	$(CC) -ansi $(LDFLAGS) -o $@ $*.c

ex103.o: ex103.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex104.o: ex104.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex105.o: ex105.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex106.o: ex106.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex107.o: ex107.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex108.o: ex108.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex109.o: ex109.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex110.o: ex110.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex112.o: ex112.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c
	
ex113.o: ex113.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex114.o: ex114.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex115.o: ex115.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex116.o: ex116.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

ex117.o: ex117.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $*.c

clean:
	rm -rvf *.o
